{
 "title": "Linkmenu g 58",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Linkmenu g 58",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>Public dashboard for this weather station: https://www.wunderground.com/weather/lt/vilnius/IVILNI45 </center>"
   }
  },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "targets": [
    { "expr": "(weather_tempf -32)/1.8 ", "legendFormat": "Outside" },
    { "expr": "(weather_tempinf -32)/1.8", "legendFormat": "Inside" }
   ]
  },
  {
   "title": "Temperature outside",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(weather_tempf-32)/1.8", "legendFormat": "Temperature C" }
   ]
  },
  {
   "title": "Humidity %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 2 },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "outside" },
    { "expr": "weather_humidityin", "legendFormat": "inside" }
   ]
  },
  {
   "title": "Humidity %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "outside" },
    { "expr": "weather_humidityin", "legendFormat": "inside" }
   ]
  },
  {
   "title": "Presure (Absolute) in hPa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(weather_baromabsin) * 33.86389",
     "legendFormat": "absolute kPa"
    },
    {
     "expr": "(weather_baromrelin) * 33.86389 ",
     "legendFormat": "relative kPa"
    }
   ]
  },
  {
   "title": "Presure (Relative) in hPa",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(weather_baromrelin) * 33.86389 ",
     "legendFormat": "hPa"
    }
   ]
  },
  {
   "title": "Solar radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 8 },
   "targets": [
    { "expr": "weather_solarradiation", "legendFormat": "W/m^2" }
   ]
  },
  {
   "title": "Solar radiation / Light",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_solarradiation", "legendFormat": "W/m^2" }
   ]
  },
  {
   "title": "Sun UVI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_uv", "legendFormat": "UVI" }
   ]
  },
  {
   "title": "Wind direction & speed",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 16 },
   "targets": [
    { "expr": "weather_winddir" },
    { "expr": "(weather_windspeedmph)*0.44704" }
   ]
  },
  {
   "title": "Wind speed m/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(weather_windspeedmph * 0.44704)"
    }
   ]
  },
  {
   "title": "Wind speed m/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "expr": "(weather_windspeedmph * 0.44704)",
     "legendFormat": "m/s^2"
    }
   ]
  },
  {
   "title": "Rain rate mm",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(weather_rainratein * 10)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Rain rate mm",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 24 },
   "targets": [
    { "expr": "(weather_rainratein * 10)", "legendFormat": "rain" }
   ]
  },
  {
   "title": "Total Rain rate (daily) mm",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 24 },
   "targets": [
    { "expr": "weather_dailyrainin * 10", "legendFormat": "rain" }
   ]
  },
  {
   "title": "Total Rain rate (montly) mm",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 24 },
   "targets": [
    { "expr": "weather_monthlyrainin * 10", "legendFormat": "rain" }
   ]
  }
 ]
}